In [105]:
import pandas as pd 
import numpy as np


In [106]:
df=pd.read_csv("spam.csv")

In [107]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [108]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [109]:
df['Spam']=df['Category'].apply(lambda x: 1 if x=='spam'else 0) 

In [110]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [111]:
from sklearn.model_selection import train_test_split

In [112]:
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.2)

In [113]:
from sklearn.feature_extraction.text import CountVectorizer

In [114]:
v=CountVectorizer()

x_train_cv=v.fit_transform(x_train.values)
type(x_train_cv)

scipy.sparse._csr.csr_matrix

In [115]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [116]:
v.get_feature_names_out().shape

(7722,)

In [117]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [118]:
v.vocabulary_

{'you': 7685,
 'sure': 6602,
 'your': 7690,
 'neighbors': 4735,
 'didnt': 2302,
 'pick': 5187,
 'it': 3750,
 'up': 7158,
 'abeg': 750,
 'make': 4322,
 'profit': 5425,
 'but': 1569,
 'its': 3757,
 'start': 6422,
 'are': 1039,
 'using': 7201,
 'to': 6907,
 'get': 3118,
 'sponsors': 6376,
 'for': 2941,
 'the': 6787,
 'next': 4763,
 'event': 2661,
 'good': 3179,
 'hear': 3372,
 'from': 3021,
 'this': 6824,
 'pain': 5046,
 'couldn': 2026,
 'have': 3350,
 'come': 1901,
 'at': 1110,
 'worse': 7580,
 'time': 6874,
 'no': 4792,
 'home': 3471,
 'work': 7566,
 'do': 2373,
 'meh': 4426,
 'can': 1622,
 'all': 908,
 'decide': 2199,
 'faster': 2778,
 'cos': 2014,
 'my': 4662,
 'sis': 6160,
 'going': 3169,
 'liao': 4091,
 'congratulations': 1962,
 'thanks': 6777,
 'friend': 3006,
 'won': 7550,
 '000': 1,
 'xmas': 7627,
 'prize': 5403,
 'claim': 1815,
 'is': 3738,
 'easy': 2516,
 'just': 3868,
 'call': 1597,
 '08718726978': 133,
 'now': 4837,
 'only': 4940,
 '10p': 255,
 'per': 5136,
 'minute': 4492,
 

In [119]:
x_train_cv=x_train_cv.toarray()

In [120]:
x_train_cv[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [121]:
np.where(x_train_cv[1]!=0)/;

(array([ 750, 1039, 1569, 2661, 2941, 3118, 3750, 3757, 4322, 4763, 5425,
        6376, 6422, 6787, 6907, 7201, 7685], dtype=int64),)

In [122]:
x_train_cv[0][2389]

0